#!/bin/bash

runtest() {
    filename="$1"
    shift
    cp "$filename" "$filename.tmp"
    ../gorpl "$@" "$filename.tmp"
    diff -u "$filename.expected" "$filename.tmp" && echo -e "\x1b[1;32mSuccess\x1b[0m: $filename" || echo -e "\x1b[1;31mFail\x1b[0m: $filename"
    echo
}

runtest "normal" hoge fuga
runtest "with-w" -w hoge fuga
runtest "without-w"  hoge fuga
runtest "with-i" -i hoge fuga
runtest "without-i"  hoge fuga
runtest "with-r" -r .oge fuga
runtest "without-r"  .oge fuga
runtest "backslash-in-to"  hoge '\1'
runtest "dollar-in-to"  hoge '$1'
runtest "dollar-in-to-with-r"  -r '(.)oge' 'X$1Y'
runtest "backslash-in-to-with-r"  -r '(.)oge' 'X\1Y'
runtest "not-utf8"  hoge fuga
